"""empty message

Revision ID: b16f114c9c28
Revises: 6886f0ecaa81
Create Date: 2023-05-18 01:08:03.917567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b16f114c9c28'
down_revision = '6886f0ecaa81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=False))
        batch_op.create_unique_constraint("email",'users', ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint("email",'users', type_='unique')
        batch_op.drop_column('users','email')

    # ### end Alembic commands ###
